### ISSUE TITLE
check restart on config change

### ISSUE THREAD

**Issue by jneo8** [jneo8/zaza-openstack-tests#2]
Similar to https://github.com/openstack-charmers/zaza-openstack-tests/blob/f3cc2ca3850eb3ce7d848aea2dd72c5579a01882/zaza/openstack/charm_tests/aodh/tests.py#L123

**Comment by mkalcok** [comment]
I would rather test that the service is running on new port after reconfiguration. We don't really care if service was restarted, rather we are interested if the config changed had an effect.

**Comment by jneo8** [comment]
> I would rather test that the service is running on new port after reconfiguration. We don't really care if service was restarted, rather we are interested if the config changed had an effect.

This make sense
